// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsEventType } from "./AnalyticsEventType";

/**
 * 1 件の Analytics イベント。
 *
 * review fix (major): SDUI v6 §10.1 / CODE_REVIEW_PROMPT §2.1 — `analyticsId` /
 * `eventType` / `timestampMs` / `context` / `serverReceivedAtMs` 以外の field を
 * silently 受け入れると後段集計でゴミが混入するため `deny_unknown_fields` を強制する。
 * 自由記述コンテキストは `context: BTreeMap` に閉じ込める設計で、トップレベルの
 * 拡張は contract 変更扱いで明示的に追加する。
 */
export type AnalyticsEvent = { 
/**
 * 対象 Block / Card の analyticsId。空文字は不可。
 */
analyticsId: string, 
/**
 * `impression` (画面に映った) / `click` (ユーザ操作)。
 */
eventType: AnalyticsEventType, 
/**
 * クライアント側 Date.now 相当 (ms epoch)。サーバは値を validate しない。
 * 設計書 §4.2.2 規約により i64 を ts-rs で number に倒す。
 * 集計の真実値は server 受信時刻側で持つ想定 (§11.2)。
 */
timestampMs: number, 
/**
 * 自由記述コンテキスト (productId / variant / experimentKey 等)。
 * 空 / 未指定は JSON で省略される (skip_serializing_if)。
 * TS 側は ts(optional) で context?: Record<string, string> として表現する。
 * client は context があれば Some、無ければ None で送る。
 */
context?: { [key: string]: string }, 
/**
 * サーバ受信時刻 (ms epoch)。設計書 §11.2 の真実値。
 * client 送信時の値は custom deserializer (`always_none`) で読み捨てて常に `None` に
 * 倒し、handler が stamp する経路だけが Some を作れる (= 偽装防止)。
 *
 * **serde quirk**: 当初は `skip_deserializing` を使っていたが、これは「フィールドが
 * 存在しない」扱いになる結果、`deny_unknown_fields` 側から見ると JSON に当該キーが
 * 乗っているだけで「unknown field」エラーになるため不採用。`deserialize_with` で
 * 「フィールドの存在は認識するが値は無視」を表現する。
 */
serverReceivedAtMs?: number, };
