// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalyticsEvent } from "./AnalyticsEvent";

/**
 * `POST /api/v1/events` で送られる batch payload。
 *
 * review fix (major): SDUI v6 §10.1 — batch 包み構造側でも未知 field を弾く。
 */
export type AnalyticsEventBatch = { events: Array<AnalyticsEvent>, };
