// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * イベント種別。
 *
 * `impression` と `click` のみ。snake_case enum で固定する (camelCase でも文字列
 * 一致するが、将来の `dwell_time` 等が来た時に明確に snake_case で受ける意図)。
 */
export type AnalyticsEventType = "impression" | "click";
