// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BadgeRole } from "./BadgeRole";
import type { CheckoutFieldAction } from "./CheckoutFieldAction";
import type { CheckoutMethodAction } from "./CheckoutMethodAction";
import type { CtaAction } from "./CtaAction";
import type { CtaIntent } from "./CtaIntent";
import type { Currency } from "./Currency";
import type { FormFieldKind } from "./FormFieldKind";
import type { Href } from "./Href";
import type { LineItemAction } from "./LineItemAction";
import type { Localizable } from "./Localizable";
import type { MediaKind } from "./MediaKind";
import type { MetaItem } from "./MetaItem";
import type { MetricItem } from "./MetricItem";
import type { ShippingMethodOption } from "./ShippingMethodOption";
import type { TextRole } from "./TextRole";

export type Block = { "type": "text", key: string, role: TextRole, content: Localizable, analyticsId?: string, } | { "type": "cta", key: string, intent: CtaIntent, label: Localizable, href: Href, 
/**
 * サーバ反映アクション。None なら href への純粋なナビゲート。
 * 詳細は `CtaAction` のドキュメントを参照。
 */
action?: CtaAction, analyticsId?: string, } | { "type": "media", key: string, kind: MediaKind, src?: string, alt?: Localizable, iconName?: string, analyticsId?: string, } | { "type": "badge", key: string, role: BadgeRole, label: Localizable, analyticsId?: string, } | { "type": "metric_list", key: string, items: Array<MetricItem>, analyticsId?: string, } | { "type": "meta_line", key: string, items: Array<MetaItem>, analyticsId?: string, } | { "type": "price", key: string, amount: number, currency: Currency, taxIncluded: boolean, analyticsId?: string, } | { "type": "eclosion_forecast", key: string, daysAhead: number, date: string, tolerance: number, analyticsId?: string, } | { "type": "divider", key: string, } | { "type": "line_item", key: string, 
/**
 * 表示テキスト用 product id。クライアント側で「商品ページに飛ぶ」リンク等に使う。
 */
productId: string, 
/**
 * 商品名 (= cart card では Localizable::Raw、商品マスタから流す)。
 */
title: Localizable, 
/**
 * サムネ画像 (なければ placeholder)。サイズ・aspect は renderer 側 CSS。
 */
imageSrc?: string, imageAlt?: Localizable, 
/**
 * 単価 (税込, 円)。MVP は JPY のみなので i64 で OK (§17 で多通貨対応)。
 * `tax_included` は OrderSummary 側でまとめて表現するためここでは持たない。
 */
unitPriceAmount: number, currency: Currency, 
/**
 * この行の数量 (>= 1; 0 になる時は Remove で消す前提)。
 */
qty: number, 
/**
 * 小計 (= unit_price_amount * qty)。サーバ側で確定値を持つ理由は、
 * クライアント計算と表示金額を絶対にずらさないため。
 */
subtotalAmount: number, 
/**
 * 商品ページへの遷移リンク (= 画像 / タイトルクリック先)。
 */
detailHref: Href, 
/**
 * "−" ボタンの action。`qty == 1` の時は None (= UI で disabled に)。
 * Some の時は LineItemAction::SetQty { qty: qty - 1 }。
 */
decrementAction?: LineItemAction, 
/**
 * "+" ボタンの action。常に Some (= LineItemAction::SetQty { qty: qty + 1 })。
 * 上限がある場合は server 側で None にして disabled にする (将来)。
 */
incrementAction: LineItemAction, 
/**
 * "削除" ボタンの action (= LineItemAction::Remove { token })。
 */
removeAction: LineItemAction, analyticsId?: string, } | { "type": "form_field", key: string, 
/**
 * PATCH URL `/checkout/shipping_field/{name}` の最後のセグメントになる識別子。
 * camelCase 推奨 (= JSON 全体の rename_all と揃う)。
 */
name: string, 
/**
 * 入力欄の上に表示するラベル (= "氏名" / "電話" 等)。i18n 対応。
 */
label: Localizable, 
/**
 * 現在値 (= server 側 checkout store の現状)。未入力なら None。
 * 空文字 ("") と None を区別できるよう Option で持つ (= 「未入力」と「空に編集中」を
 * 混同しない)。
 */
value?: string, 
/**
 * 必須かどうか。client 側 disabled / aria-required の判定にも使う。
 */
required: boolean, 
/**
 * HTML autocomplete attribute (= "name" / "tel" / "postal-code" / "address-level1" / "street-address")。
 * 未指定なら autocomplete を出さない。
 */
autocomplete?: string, 
/**
 * プレースホルダ (= "150-0001" など)。i18n 対応。
 */
placeholder?: Localizable, 
/**
 * このフィールドに対する validation エラー文 (= "未入力です" など)。
 * None なら何も出さない。Some なら field 直下に赤字で表示。
 */
validationError?: Localizable, 
/**
 * 入力種別 (Text / Tel / PostalCode / Select)。Select の時は options を持つ。
 */
kind: FormFieldKind, 
/**
 * この field を更新する action。client 側は debounce 後に invoke する。
 */
patchAction: CheckoutFieldAction, analyticsId?: string, } | { "type": "shipping_method_picker", key: string, 
/**
 * 全候補 (空配列なら client 側で「配送方法が登録されていません」を出す)。
 * 1 件しかない場合も radio で出す (= 将来 2 件目が追加された時に UI が壊れない)。
 */
options: Array<ShippingMethodOption>, 
/**
 * 現在選択中の option id。`options[].id` のいずれかに含まれる前提
 * (= server 側で必ず default を指すよう構築する)。
 */
selectedId: string, 
/**
 * この picker を更新する action。client 側は radio change 即 invoke。
 */
patchAction: CheckoutMethodAction, analyticsId?: string, } | { "type": "order_summary", key: string, 
/**
 * 行数 (= LineItem の件数)。
 */
lineCount: number, 
/**
 * 数量合計 (= 全 LineItem の qty 合計)。
 */
totalQty: number, subtotalAmount: number, 
/**
 * 配送料 (= None なら配送料行を出さない / `Some(0)` なら "送料無料" 表示)。
 */
shippingAmount?: number, 
/**
 * 消費税 (= None なら税行を出さない / `Some(n)` なら "(うち消費税 n 円)")。
 */
taxAmount?: number, 
/**
 * 最終合計 (= subtotal + shipping; tax は subtotal に含む想定)。
 */
totalAmount: number, currency: Currency, analyticsId?: string, };
