// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CartRegions } from "./CartRegions";
import type { CartVariant } from "./CartVariant";
import type { Experiment } from "./Experiment";
import type { ProductDetailRegions } from "./ProductDetailRegions";
import type { ProductDetailVariant } from "./ProductDetailVariant";
import type { ProductFeatureRegions } from "./ProductFeatureRegions";
import type { ProductFeatureVariant } from "./ProductFeatureVariant";

export type CardBlock = { "template": "product_feature", 
/**
 * §4.6 の規約に従う不変 ID (データ主キー / 構造化 ID / 複合 ID のいずれか)。
 */
id: string, variant?: ProductFeatureVariant, experiment?: Experiment, 
/**
 * 未指定時は §11.4 のフォールバックにより `id` を流用する。
 */
analyticsId?: string, regions: ProductFeatureRegions, } | { "template": "product_detail", id: string, variant?: ProductDetailVariant, experiment?: Experiment, analyticsId?: string, regions: ProductDetailRegions, } | { "template": "cart", id: string, variant?: CartVariant, experiment?: Experiment, analyticsId?: string, regions: CartRegions, };
