// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `cart` テンプレートの variant。
 *
 * **Default vs Empty を分けない理由**:
 *   "0 件" の判定は `regions.items.len() == 0` で renderer 側が決められる。
 *   別 variant にすると「items が空でも Default を返す → 矛盾」を server が壁打ちする
 *   コストが増える。empty state の見た目分岐は client 側で 1 行 (= Show when=) で完結。
 */
export type CartVariant = "default";
