// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * `cart` テンプレートの許容リージョン: header / items / shipping /
 * shipping_method / summary / cta。
 *
 *   - header          : "あなたのカート (3 件)" などの見出し (= Text 1 件想定、空 OK)
 *   - items           : LineItem の列 (空 = カート空)
 *   - shipping        : 配送先入力フォーム (= FormField の列)
 *   - shipping_method : 配送方法ピッカー (= ShippingMethodPicker 1 件)
 *   - summary         : OrderSummary 1 件 (空カート時は [])
 *   - cta             : "Stripe で決済" / "買い物を続ける" などの CTA
 *
 * **空カート時の表現**:
 *   `items` / `shipping` / `shipping_method` / `summary` を全て [] にし、
 *   `cta` には「買い物を続ける」だけ入れる。
 *   client 側は `Show when={items.length > 0}` で empty state を切り替える。
 *   Variant を Empty で分けない理由は blocks.rs の CartVariant コメント参照。
 *
 * **header に Text 以外を入れない**:
 *   今は Text 1 件想定だが、将来「カートはあと N 円で送料無料です」のような
 *   Promo Badge を増やす余地を残して `Vec<Block>` のまま。
 *
 * **shipping の順序**:
 *   FormField を 5 件 (氏名 / 電話 / 郵便番号 / 都道府県 / 住所) の順で並べる。
 *   グリッド配置 (2 カラム + 住所が full width) は client renderer 側 CSS で実現。
 *   block 単位で reorder したければサーバが Vec の順序を入れ替えるだけ。
 *
 * **shipping_method を別 region にする理由**:
 *   shipping (= 入力フォーム) と shipping_method (= radio ピッカー) で
 *   - section 見出し (§02 お届け先 / §03 配送方法) が違う
 *   - empty state の出し分けが独立 (= 配送方法だけ全部 sold out というケースは無いが
 *     将来 "配送先確定後に方法を表示" のような二段構成にする余地)
 *   をきれいに分離するため。1 region に詰めると section 跨ぎでルーティング順を再構築する
 *   必要が出る。
 */
export type CartRegions = { header: Array<Block>, items: Array<Block>, 
/**
 * 配送先入力フォーム (= FormField の列)。空配列なら section 省略。
 */
shipping: Array<Block>, 
/**
 * 配送方法ピッカー (= ShippingMethodPicker 1 件)。空配列なら section 省略。
 */
shippingMethod: Array<Block>, summary: Array<Block>, cta: Array<Block>, };
