// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtaAction = { "type": "add_to_cart", productId: string, qty: number, } | { "type": "toggle_watch", productId: string, } | { "type": "stripe_checkout" };
