// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Href } from "./Href";
import type { Localizable } from "./Localizable";

/**
 * 1 つのチップ = 1 つの絞り込み値。
 *
 * **なぜ既存の `Block::Cta` を流用しないか**:
 *   Cta は「ページ遷移 or サーバ反映 action」を表す汎用部品。filter chip は
 *   「現在の選択を toggle して URL を書き換える」という固有の挙動を持ち、
 *   `selected` flag や `count` (faceted search) など固有データも持つ。
 *   将来 chip 専用の UI (削除 X ボタン / カウント badge など) を追加する余地を
 *   残すため、独立 struct とする。
 */
export type FilterChipItem = { 
/**
 * chip の値識別子 (例: "live" / "supply" / "easy")。group 内一意。
 */
key: string, 
/**
 * 表示ラベル (例: "生体" / "用品" / "初心者向け")。
 */
label: Localizable, 
/**
 * 現在のクエリでこの値が選択中なら true。
 * クライアントは true → primary inverse、false → outlined のように描き分ける。
 */
selected: boolean, 
/**
 * クリック先 URL。**toggle 後の状態** を表す:
 *   - 自分が selected → 自分を除いた URL (= 解除)
 *   - 自分が not selected → 自分を追加した URL (= 適用)
 */
href: Href, 
/**
 * 現クエリ条件下でこの値を選んだ場合の該当件数 (faceted search)。
 * 「他軸の絞り込みは維持し、この軸の値を **この chip に切り替えた** ら何件か」。
 * 0 件のチップも非表示にせず `Some(0)` を返す (= UI 側で disabled 表示する余地)。
 * 集計を切る (= 全削除して None に戻す) 場合は handler 側の build_filter_bar を変える。
 */
count?: number, 
/**
 * click analytics 用 ID。`filter.<group_key>.<chip_key>` 形式を推奨。
 */
analyticsId?: string, };
