// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterChipItem } from "./FilterChipItem";
import type { Localizable } from "./Localizable";

/**
 * 絞り込み 1 軸ぶん (例: 「カテゴリ」「飼育難度」)。
 */
export type FilterGroup = { 
/**
 * クエリパラメータ名 (`?category=...` の "category")。group 内ユニーク。
 */
key: string, 
/**
 * この group のラベル (例: "カテゴリ" / "飼育難度")。
 */
label: Localizable, 
/**
 * この軸の選択肢たち。少なくとも 1 件以上を期待する。
 */
chips: Array<FilterChipItem>, };
