// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterGroup } from "./FilterGroup";

/**
 * 絞り込みエリア全体。複数の `FilterGroup` を縦に並べる想定。
 */
export type FilterBar = { groups: Array<FilterGroup>, };
