// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectOption } from "./SelectOption";

/**
 * FormField の入力種別。`tag = "inputType"` で discriminate する。
 *
 * **なぜ tag を "kind" にしないか**: 親 `Block::FormField` の名前付きフィールドが
 * `kind: FormFieldKind` なので、内側でも `kind` を tag に使うと
 * `"kind": { "kind": "text" }` と冗長になる。`inputType` にすれば
 * `"kind": { "inputType": "text" }` となり、TS でも `block.kind.inputType === "text"`
 * が読みやすい。
 */
export type FormFieldKind = { "inputType": "text" } | { "inputType": "tel" } | { "inputType": "postal_code" } | { "inputType": "select", options: Array<SelectOption>, };
