// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ハイパーリンクの URL / パス。許容スキーマ・ホストのルールは §10.2。
 *
 * `serde(transparent)` により JSON では普通の文字列として表現される。
 * フロント側では `branded.ts` レイヤで branded 型に持ち上げる (§7.5)。
 */
export type Href = string;
