// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineItemAction = { "type": "set_qty", token: string, qty: number, } | { "type": "remove", token: string, };
