// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { I18nKey } from "./I18nKey";
import type { ParamValue } from "./ParamValue";

/**
 * 翻訳対象テキスト (`i18n`) と動的生成テキスト (`raw`) の両方を許容する union。
 *
 * - `i18n`: フロントで辞書を引いて描画する想定。`params` で補完文字列を渡す
 * - `raw` : サーバ側で組み立て済みの最終文字列。商品名・人名など翻訳しない値
 */
export type Localizable = { "source": "i18n", key: I18nKey, params?: { [key: string]: ParamValue }, } | { "source": "raw", text: string, };
