// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaItemAlign } from "./MetaItemAlign";
import type { MetaLineItemRole } from "./MetaLineItemRole";

export type MetaItem = { key: string, role: MetaLineItemRole, 
/**
 * §12.6 の例外: `value` は `Localizable` ではなく素の文字列。
 * 商品 ID / 店舗名 / SKU など、翻訳対象でないラベル用。
 */
value: string, align?: MetaItemAlign, };
