// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Localizable } from "./Localizable";

export type MetricItem = { key: string, label: Localizable, value: Localizable, };
