// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Href } from "./Href";

/**
 * 1 ページ分のリンク (= ページャに並ぶ各セル)。
 *
 * **kind** で「数字リンク」「ellipsis (...)」を区別する:
 *   - `Page { number, href, selected }` — クリック可能なページ番号
 *   - `Ellipsis` — 省略表示 (1 ... 4 5 6 ... 10 のような中略)
 *
 * page link を flat な Vec<PageLink> で表現するのは、render 側で `for (link of pages)`
 * するだけで済むようにするため。range collapse のロジックは server に集約。
 */
export type PageLink = { "kind": "page", 
/**
 * 1 始まりのページ番号。
 */
number: number, 
/**
 * 遷移先 URL。
 */
href: Href, 
/**
 * 現在ページなら true (= aria-current="page" / disabled link 想定)。
 */
selected: boolean, } | { "kind": "ellipsis" };
