// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Href } from "./Href";
import type { PageLink } from "./PageLink";

/**
 * ページング UI 全体。
 *
 * **prevHref / nextHref が None** の時は disabled (first/last page を超えるリンクを描かない)。
 * クライアントは `data-disabled="true"` 付きの span などで render すればよい。
 */
export type Pagination = { 
/**
 * 現在のページ番号 (1 始まり)。
 */
page: number, 
/**
 * 1 ページあたり件数。
 */
perPage: number, 
/**
 * 全件数 (filter + search 適用後 / sort・paginate 前)。
 */
totalCount: number, 
/**
 * 全ページ数 (= ceil(total_count / per_page); 0 件なら 1)。
 */
totalPages: number, 
/**
 * 前ページへの URL。first page なら None (= disabled)。
 */
prevHref?: Href, 
/**
 * 次ページへの URL。last page なら None (= disabled)。
 */
nextHref?: Href, 
/**
 * ページ番号リンクのリスト (collapse 済み: 1 / current±2 / last + ellipsis)。
 */
pages: Array<PageLink>, 
/**
 * click analytics 用 ID prefix。`pagination.page` 形式を推奨 (個別ページは context に number を入れる)。
 */
analyticsId?: string, };
