// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `product_detail` テンプレートの variant。
 * MVP では Default のみ。将来「ペア販売」「予約商品」等の表示差を
 * バリアントで切り替える可能性に備えて enum で型を切っておく。
 */
export type ProductDetailVariant = "default";
