// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `product_feature` テンプレートの variant (マーチャンダイジング用)。
 * `Experiment.bucket` (A/B テスト) とは独立 (§11.3)。
 */
export type ProductFeatureVariant = "default" | "featured" | "compact";
