// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * `product_detail` テンプレートの許容リージョン:
 *   gallery / hero / spec / pricing / cta / promise。
 *
 * **product_feature との違い**:
 *   一覧カードは「画像 + 名前 + 価格」の濃縮表示だが、詳細ページは
 *   - gallery : 大画像 + サムネ列 (複数 Media 対応 / 動画埋め込みは将来)
 *   - hero    : 店舗 byline / タイトル / 学名 / chip 群
 *   - spec    : 個体スペック (サイズ / 性別 / 羽化日 / 累代 / 産地 / ブリーダー)
 *   - pricing : 価格 (税込 / 配送料注記)
 *   - cta     : カートに追加 / カートを見る / ウォッチ など複数アクション
 *   - promise : 安心保証カード (死着補償・温度制御便など `text` + 末尾 `cta`)
 *
 * **promise を独立 region にした理由**:
 *   - 視覚的には「囲み card」として hero/cta とは別レイアウトで描画される
 *   - 用品カードでは存在しない / 生体カードのみ表示する、という出し分けがしやすい
 *   - 将来、保証種別が増えた時に block primitive を増やす前に「区画ごと省略」できる
 *
 * 空配列の region は client renderer 側 (`<Show when={...length > 0}>`) で section ごと
 * 省略する。サーバから明示的に omit したい場合も `[]` で送る (deserialize 時に default で
 * `Vec::new()` になるため、JSON 側で省略しても OK)。
 */
export type ProductDetailRegions = { gallery: Array<Block>, hero: Array<Block>, spec: Array<Block>, pricing: Array<Block>, cta: Array<Block>, 
/**
 * 安心保証など「保証・補償」を訴求する小さな card 領域。
 * 一般的に `text` (eyebrow / caption) を 3 〜 4 件並べ、末尾に `cta` を 1 件置く。
 */
promise: Array<Block>, };
