// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardBlock } from "./CardBlock";
import type { FilterBar } from "./FilterBar";
import type { Pagination } from "./Pagination";
import type { SearchBox } from "./SearchBox";
import type { SortBar } from "./SortBar";

/**
 * 一覧 endpoint (`GET /api/v1/cards/products?...`) のレスポンス shell。
 *
 * review fix (major): SDUI v6 §10.1 / CODE_REVIEW_PROMPT §2.1 — list shell 系も
 * SDUI 契約に乗る型なので `deny_unknown_fields` を付けて、サーバ実装の typo や
 * 旧クライアントの古い field が silently 通る事故を起こさないようにする。
 * 任意フィールド (filter_bar / sort_bar / search_box / pagination) は
 * `Option` + `skip_serializing_if` の組み合わせでそのまま optional に保たれる。
 */
export type ProductListResponse = { 
/**
 * 絞り込み UI 群。
 * `None` の時はフロント側で filter bar を描かない (= フィルタ機能 OFF)。
 * MVP では常に Some で返す (= ページにフィルタが見えている状態)。
 */
filterBar?: FilterBar, 
/**
 * 並び替え UI。
 * `None` の時はフロント側で sort dropdown を描かない (= 並び替え機能 OFF)。
 * MVP では常に Some で返す。
 */
sortBar?: SortBar, 
/**
 * 検索 box。`None` の時は SearchBox 非表示。
 * 現クエリの `?q=` の値もここに入って戻ってくる (= controlled input の初期値)。
 */
searchBox?: SearchBox, 
/**
 * ページング情報。`None` の時はフロント側で PageBar を描かない。
 * 結果が 1 ページ以下でも返す (PageBar 側で「<=1 ならコンパクト表示 / 非表示」を選ぶ)。
 */
pagination?: Pagination, 
/**
 * 現在のクエリで絞られた商品カード列。サーバ側で `sort_bar.current` の指示通りに並べ済み。
 */
cards: Array<CardBlock>, };
