// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * `product_feature` テンプレートの許容リージョン: header / media / meta / body / footer。
 *
 * 例: `headline` / `actions` を含めようとすると deserialize で 400。
 */
export type ProductFeatureRegions = { header: Array<Block>, media: Array<Block>, meta: Array<Block>, body: Array<Block>, footer: Array<Block>, };
