// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * リージョン名。テンプレートが許容する集合は `<Template>Regions` 側で表現する。
 */
export type RegionName = "header" | "media" | "meta" | "headline" | "body" | "actions" | "footer";
