// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Href } from "./Href";
import type { Localizable } from "./Localizable";

/**
 * 検索 box。
 *
 * **submitHref** はクエリから `q` を「抜いた」base URL を返す。フロントは:
 *   - JS 無し: `<form action="{submitHref}" method="get">` + 内部の input name=`paramName`
 *     で送信。filter / sort 等の他 params は submitHref に含まれているので維持される。
 *   - JS 有り: input change を debounce → `submitHref` の query string を URLSearchParams で
 *     parse → `q` を上書き → navigate。
 *
 * `paramName` を field として持つ理由: 将来 `?keyword=` 等にリネームしたくなった時、
 * クライアントを変えずに移行できる (= server だけで決められる)。
 */
export type SearchBox = { 
/**
 * 現在の検索文字列 (空 / 未指定なら None)。controlled input の初期値として使う。
 */
query?: string, 
/**
 * 入力欄の placeholder。空文字でも構わない。
 */
placeholder: Localizable, 
/**
 * submit 先 (q を抜いた base URL)。filter / sort などは含まれている。
 */
submitHref: Href, 
/**
 * query string のパラメータ名 (通常 "q")。
 */
paramName: string, 
/**
 * click/submit analytics ID。`search.submit` 形式を推奨。
 */
analyticsId?: string, };
