// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Localizable } from "./Localizable";

export type SelectOption = { 
/**
 * 一意な値 (= <option value=>)。Select の現在値はこれと比較される。
 */
id: string, 
/**
 * 表示ラベル (i18n 対応)。
 */
label: Localizable, };
