// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Localizable } from "./Localizable";

export type ShippingMethodOption = { 
/**
 * 一意な ID (= radio の value)。例: "cold" / "normal"。
 */
id: string, 
/**
 * 表示名 (= "温度制御便（推奨）")。i18n 対応。
 */
name: Localizable, 
/**
 * 補足説明 (= "生体含むため必須設定 · 15〜25℃")。i18n 対応。
 */
description: Localizable, 
/**
 * 配送料 (税込, 円)。MVP は JPY のみ。
 */
amount: number, currency: Currency, };
