// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Href } from "./Href";
import type { Localizable } from "./Localizable";

/**
 * 1 つの並び順候補。filter chip と似ているが、selected 切替時に
 * 「自分を抜く / 自分を追加する」のではなく「自分に置き換える」のが違い。
 */
export type SortOption = { 
/**
 * sort 値識別子 (例: "name" / "price_asc" / "price_desc" / "new")。
 */
key: string, 
/**
 * 表示ラベル (例: "名前順" / "価格(安い順)")。
 */
label: Localizable, 
/**
 * 現在の `?sort=` がこの値なら true。クエリ未指定時は default 値が selected。
 */
selected: boolean, 
/**
 * クリック先 URL — この sort に **置き換えた** 状態の URL。
 * filter chip 群 (`?category=` 等) は維持される。
 */
href: Href, 
/**
 * click analytics 用 ID。`sort.<key>` 形式を推奨。
 */
analyticsId?: string, };
