// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOption } from "./SortOption";

/**
 * 並び替え UI 全体。1 ページに 1 つだけ。
 *
 * **current** はクエリ未指定時のデフォルトを含めた「現在適用中の sort key」を返す。
 * クライアントは current === option.key で selected を判定できるが、
 * `SortOption.selected` も明示的に持たせて renderer の責務を減らしている。
 */
export type SortBar = { 
/**
 * 現在適用中の sort key (例: "name" / "price_asc" / "new")。
 * クエリ未指定時は default value で埋まる。
 */
current: string, 
/**
 * 並び順候補。少なくとも 1 件以上。
 */
options: Array<SortOption>, };
