// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextRole = "eyebrow" | "headline" | "subhead" | "lead" | "body" | "caption" | "byline";
